{
 "title": "netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}\r"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdc\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/usr/lib/wsl\"}"
    }
   ]
  },
  {
   "title": "MemFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}"
    }
   ]
  }
 ]
}